「Contractを作成する」の修正
a-mitani/mastering-ethereum pull request #12
Opened 2017-01-07 17:03 UTC by gacktomo

・MacOSXへのsolcインストール手順の修正
・コントラクト作成時の変数宣言に不要なvarを削除
・誤字の修正

2017-02-01 13:22 UTC, a-mitani approved these changes

2017-02-01 13:30 UTC, a-mitani requested changes
JavaScriptでは、厳格モード（use strict）ではvarを用いた宣言が必須のため、varは残しておくべきだと考えています。

問題なければ、この変更（コミット）を抜いて、再度プルリクお願いできますか？

2017-02-01 17:31 UTC, gacktomo commented
varを記述しました。確認お願いします。

2017-02-06 05:11 UTC, merged

2017-02-06 05:17 UTC, a-mitani commented
マージしました。ありがとうございます。